blank_issues_enabled: false
contact_links:
  - name: 💬 Question
    url: https://github.com/caret-labs-co/.github/blob/main/docs/SUPPORT.md#questions
    about: Open a discussion via the Discussions tab to ask a question about the project
